server:
  port: 8081
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/kosmoscan
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

file:
  storage:
    location: ${FILE_STORAGE_LOCATION:./uploads}

analysis-service:
  url: http://api-gateway:8080/api/analysis